[package]
name = "elesardelavega/dibujooasis"
version = "0.1.0"
description = "WordPress/PHP App"

[dependencies]
# Usar un runtime PHP simple (si es diferente a la versión "latest" que tenías)
php = "wasmer/php@1.2.0" 

[command]
name = "start"
# Usar el comando de Wasmer para PHP
module = "php:server"

[fs]
"./" = "/"